server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local

  application:
    name: nexcore-core

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  




